require:
  - rubocop-rspec

inherit_from:
  - ./config/rubocop-suse.yml

RSpec/DescribeClass:
  Exclude:
    - ./spec/requests/**/*

Documentation:
  Enabled: False

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

AllCops:
  Exclude:
    # Files that are out of our control and that are not excluded in the
    # default config of rubocop.
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
